FROM ubuntu:22.04
ENV RUNNER_ALLOW_RUNASROOT=1

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install git -y
RUN apt-get install curl -y

RUN mkdir actions-runner
WORKDIR /actions-runner

RUN curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
RUN echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d actions-runner-linux-x64-2.317.0.tar.gz" | sha256sum -c -
RUN tar xzf actions-runner-linux-x64-2.317.0.tar.gz
RUN rm actions-runner-linux-x64-2.317.0.tar.gz

RUN ./bin/installdependencies.sh
RUN ./config.sh --url https://github.com/dzamakhaiev/messenger --token ABQ7XMAGO5TIVP66UT6G663GTUFQU
CMD ./run.sh