MESSENGER_HOST = '192.168.50.100'
MESSENGER_PORT = 5000
MESSENGER_URL = f'http://{MESSENGER_HOST}:{MESSENGER_PORT}'
HEALTH = '/health'
API = '/api'
LOGIN = API + '/login/'
USERS = API + '/users/'
MESSAGES = API + '/messages/'
