import os
CI_RUN = int(os.environ.get('CI_RUN', 0))

# PROD SSL URL
MESSENGER_HOST = '192.168.50.100'
MESSENGER_PORT = 5000
MESSENGER_URL_PROD = f'https://{MESSENGER_HOST}:{MESSENGER_PORT}'

# CI SSL URL
MESSENGER_HOST_SSL_CI = '172.29.152.100'
MESSENGER_PORT_SSL_CI = 5001
MESSENGER_URL_SSL_CI = f'https://{MESSENGER_HOST_SSL_CI}:{MESSENGER_PORT_SSL_CI}'

# CI URL
MESSENGER_HOST_CI = '172.29.152.100'
MESSENGER_PORT_CI = 5002
MESSENGER_URL_CI = f'http://{MESSENGER_HOST_CI}:{MESSENGER_PORT_CI}'

HEALTH = '/health'
API = '/api'
LOGIN = API + '/login/'
LOGOUT = API + '/logout/'
USERS = API + '/users/'
MESSAGES = API + '/messages/'
